version: '3.8'
services:
  application:
    image: ahmedukamel/demo:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      - database
    #        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/test_app_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=SomeStrongPass#123
    networks:
      - test-application-network
    container_name: application_container
  database:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=test_app_db
      - MYSQL_ROOT_PASSWORD=SomeStrongPass#123
    networks:
      - test-application-network
    container_name: database_container
    volumes:
      - mysql-db-volume:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      retries: 10
#      interval: 3s
#      timeout: 30s
volumes:
  mysql-db-volume:
networks:
  test-application-network:
    name: springboot-mysql-network