spring:
  application:
    name: ahmed-docker-app
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect